apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-catalogue
  labels:
    name: configmap-catalogue
    project: roboshop
data:
  # property-like keys; each key maps to a simple value
  MONGO: "true"
  MONGO_URL: "mongodb://service-mongodb:27017/catalogue"


apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: deployment-catalogue
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-catalogue
      project: roboshop
  template:
    metadata:
      labels:
        name: deployment-catalogue
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: pavankotha9550/catalogue:v1
        envFrom:
        - configMapRef:
            name: configmap-catalogue

apiVersion: v1
kind: Service
metadata:
  name: service-catalogue
  namespace: roboshop
  labels:
    name: roboshop
    server: service-catalogue
    env: dev
spec:
  selector:
    name: deployment-catalogue
    project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
