apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    env: dev
  annotations:
    description: "example for annotations"
    url: "http://roboshop.com"
spec:
  containers:
  - name: nginx
    image: nginx