apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: resources
    project: roboshop
    env: dev
  annotations:
    description: "pod description for resources limiting"
    url: "http://roboshop.com"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "150m"