apiVersion: v1
kind: Service
metadata:
  name: service-demo
  labels:
    name: roboshop
    server: nginx-frontend
    env: dev
spec:
  selector:
    purpose: demo
  ports:
    - protocol: TCP
      port: 80
      targetport: 80 
------- 
apiVersion: v1
kind: Pod
metadata:
  name: roboshop
  labels:
    purpose: demo
spec:
  containers:
  - name: nginx
    image: nginx 