apiVersion: v1
kind: Service
metadata:
  name: node-port-demo
  labels:
    name: roboshop
    server: nodeport-nginx-frontend
    env: dev
spec:
  type: NodePort
  selector:
    purpose: nodeport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
####
# apiVersion: v1
# kind: Pod
# metadata:
#   name: roboshop
#   labels:
#     purpose: nodeport
# spec:
#   containers:
#   - name: nginx
#     image: nginx 