apiVersion: v1
kind: Service
metadata:
  name: LB-port-demo
  labels:
    name: roboshop
    server: LB-nginx-frontend
    env: dev
spec:
  type: LoadBalancer
  selector:
    purpose: LB
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
####
apiVersion: v1
kind: Pod
metadata:
  name: roboshop
  labels:
    purpose: LB
spec:
  containers:
  - name: nginx
    image: nginx 