apiVersion: v1
kind: Service
metadata:
  name: lb-port-demo
  labels:
    name: roboshop
    server: lb-nginx-frontend
    env: dev
spec:
  type: LoadBalancer
  selector:
    purpose: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 

apiVersion: v1
kind: Pod
metadata:
  name: roboshop--LB-service
  labels:
    purpose: lb
spec:
  containers:
  - name: nginx
    image: nginx 