apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: deployment-demo
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      name: deployment-demo
      project: roboshop
  template:
    metadata:
      labels:
        name: deployment-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
