apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-dynamic
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0e89d560dced6dc8b

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce # Must match the PV's access mode
  storageClassName: "" # Must match the PV's storageClassName
  volumeName: ebs-dynamic # This binds it directly to the reset PV
  resources:
    requests:
      storage: 5Gi # Must be less than or equal to the PV's capacity


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: roboshop
    server: lb-nginx-frontend
    env: dev
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c 
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: ebs-dynamic
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: ebs-claim

---

apiVersion: v1
kind: Service
metadata:
  name: lb-port-demo
  labels:
    name: roboshop
    server: lb-nginx-frontend
    env: dev
spec:
  type: LoadBalancer
  selector:
    name: roboshop
    server: lb-nginx-frontend
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 