apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    name: deployment-mongodb
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-mongodb
      project: roboshop
  template:
    metadata:
      labels:
        name: deployment-mongodb
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: pavankotha9550/mongodb:v1

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
  namespace: roboshop
  labels:
    name: roboshop
    server: service-mongodb
    env: dev
spec:
  selector:
    name: deployment-mongodb
    project: roboshop
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
