apiVersion: v1
kind: Secret
metadata:
  name: secret-rabbitmq
  labels:
    project: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    name: deployment-rabbitmq
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-rabbitmq
      project: roboshop
  template:
    metadata:
      labels:
        name: deployment-rabbitmq
        project: roboshop
    spec:
      containers:
      - name: rabbitmq
        image: pavankotha9550/rabbitmq:v1
        envFrom:
        - secretRef:
            name: secret-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: service-rabbitmq
  namespace: roboshop
  labels:
    name: roboshop
    server: service-rabbitmq
    env: dev
spec:
  selector:
    name: deployment-rabbitmq
    project: roboshop
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
